# Generated by Django 3.1.1 on 2020-10-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
